### ISSUE TITLE
插入html代码会直接被浏览器解析，没有处理好啊！问题如下

### ISSUE THREAD

**Issue by iszmxw** [heyanlong/summernote-ext-highlight#11]
@heyanlong 代码插入编辑器后直接被解析了，希望能够在代码插入编辑器之前将
<html></html>
<script></script>
<p></p>
<a></a>
等等标签转以后在插入到编辑器中

![image](https://user-images.githubusercontent.com/31272102/48926516-cc87dc00-ef09-11e8-9845-ad3ca58b65eb.png)
![image](https://user-images.githubusercontent.com/31272102/48926525-d90c3480-ef09-11e8-93b3-7de72625a48c.png)
![image](https://user-images.githubusercontent.com/31272102/48926535-e75a5080-ef09-11e8-8ffd-c17361283350.png)

**Comment by iszmxw** [comment]
我稍微处理了一下大概在110行左右
![image](https://user-images.githubusercontent.com/31272102/48927033-c5fb6380-ef0d-11e8-9763-16fba03b8430.png)

> 下面是修改后方法



$extHighlightBtn.one('click', function (event) {

                            event.preventDefault();

                            //转义后的html
                            $code = $extHighlightCode.val().replace(/[<>&"]/g,function(c){return {'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c];});

                            //插入的代码类型
                            $type = $extHighlightSelect.val();

                            deferred.resolve(self.createCodeNode($code, $type));

                        });

不知道楼主有没有其他更好的办法

**Comment by heyanlong** [comment]
提交merge request吧

**Comment by iszmxw** [comment]
@heyanlong 这个不会啊，没弄过
