### ISSUE TITLE
May I register this on awesome-summernote?

### ISSUE THREAD

**Issue by lqez** [heyanlong/summernote-ext-highlight#2]
Thank you for making nice plugin for summernote.
I'm a contributor of summernote and awesome-summernote. I found this plugin on issue list of summernote.

https://github.com/summernote/awesome-summernote curates cool list of summernote plugins. 

So, may I register this on there?

**Comment by heyanlong** [comment]
@lqez Yes, I'm glad you can add

**Comment by lqez** [comment]
@heyanlong Thanks! 
https://github.com/summernote/awesome-summernote/commit/3c14ad69440d2fd29436a12ee39246ffa94f8dcd
Best wishes for a happy new year !
