### ISSUE TITLE
it doesn't work with latest summernote.

### ISSUE THREAD

**Issue by semplon** [heyanlong/summernote-ext-highlight#4]
Hello, I try this and it seems it doesn't work with the latest summernote >= v0.8.1

Thanks

**Comment by heyanlong** [comment]
This version is compatible with 0.7.1. Wait, I'll update

**Comment by heyanlong** [comment]
@semplon Can you give me an error log it?

**Comment by semplon** [comment]
i'm sorry. i don't have error log. i test it with jsfiddle and didn't save it.

**Comment by heyanlong** [comment]
@semplon That night, I fix it, I'm working. Or you submit a patch to fix.

**Comment by semplon** [comment]
hi @heyanlong i'm not fast enough with javascript. maybe i'll wait for your update :+1:

**Comment by heyanlong** [comment]
@semplon ok

**Comment by heyanlong** [comment]
@semplon Sorry, I did not find the problem. with 0.8.1

**Comment by semplon** [comment]
hmm it seems weird. I'll try again later. 

thanks
